### ISSUE TITLE
Program is allowed to move to Mode Selection even if deck loading causes an error

### ISSUE THREAD

**Issue by BLimmie** [ucsb-cs56-projects/cs56-utilities-flashcards#16]
Reproduction:
1. Make garbage file
2. Load it using the load button in the Main Menu
3. Program moves to Mode Selection

Suggested points: 100+

**Comment by scottpchow23** [comment]
F17 OK (100 pts)

Could be more if it's particularly nasty.

**Comment by scottpchow23** [comment]
100 xp

W18 OK
