### ISSUE TITLE
Edit existing decks

### ISSUE THREAD

**Issue by jmangel** [ucsb-cs56-projects/cs56-utilities-flashcards#4]
Currently, when you load an existing deck from a file, your only options are to 'study' or 'quiz'. Add functionality to edit these old decks, probably through the same interface as creating a new one

**Comment by jmangel** [comment]
F16 OK (100 pts)

**Comment by scottpchow23** [comment]
F17 OK (200 pts)

**Comment by scottpchow23** [comment]
200 xp

W18 OK
